#!/bin/sh

# -----
# Install script for MacPorts setup.
#
# Usage: sh setup [-f]
# -----

# Source shared functions, etc.
. ../common.sh || exit 2

# TODO: Try to factor out common script-level options.
mp_FORCE=$FORCE
while getopts f opt; do
    case $opt in
        f) mp_FORCE=-f ;;
    esac
done
shift $(($OPTIND - 1))

# Install zsh customizations.
# TODO: Support custom zsh configuration location.
mkdir -p "$HOME/.zsh/startup"
ln_abs -s $mp_FORCE macports.zsh "$HOME/.zsh/startup/macports.zshenv"
