#!/bin/sh

# -----
# Install script for Git setup.
#
# Usage: sh setup [-f] [TARGET]
# -----

# Source shared functions, etc.
. ../common.sh || exit 2

# TODO: Try to factor out common script-level options.
git_FORCE=$FORCE
while getopts f opt; do
    case $opt in
        f) git_FORCE=-f ;;
    esac
done
shift $(($OPTIND - 1))

git_TARGET=${1:-${TARGET:-$HOME}}
for src in git*; do
    ln_abs -s $git_FORCE "$src" "$git_TARGET/.$src"
done
