divert(`-1')
changequote(`«', `»')
changecom

-----

Print the common header. Each line is prefixed with "# " by default; the
caller may change this by specifying an argument.

define(«__header__», «dnl
ifelse(«$#», «0», «# », «$1»)dnl
Generated by dotfiles setup: syscmd(«date»)dnl
ifelse(«$#», «0», «# », «$1»)-----dnl
»)

divert«»dnl
