#!/bin/sh

# -----
# Master install script for system configuration.
#
# Usage: sh setup [-f]
# -----

# Check for options.
FORCE=
while getopts f opt; do
    case $opt in
        f) FORCE=-f ;;
    esac
done
shift $(($OPTIND - 1))

# TODO: Support customized target directory.
#TARGET=$HOME

# Source all "setup" files in directory tree.
for SETUP in $(find . -name setup -type f); do
    DIR=$(dirname "$SETUP")
    SCRIPT=$(basename "$SETUP")
    [ "x$DIR" = "x." ] || [ -z "$DIR" ] || [ -z "$SCRIPT" ] && continue

    (cd "$DIR" && . "./$SCRIPT" $FORCE)
done
