# Source topic scripts.
save_vars LC_COLLATE
LC_COLLATE=C
for script in dummy $ZDOTDIR/zlogin.d/*.zsh(N-^/); do
    if [[ $script = dummy ]]; then
        restore_vars LC_COLLATE
    else
        . $script
    fi
done
unset script

unset_sh_helper_functions
