# zsh/_zsh/zprofile
# -----------------
#
# Written in 2015-2016, 2018, 2020-2021 by Lawrence Velázquez
# <vq@larryv.me>.
#
# To the extent possible under law, the author(s) have dedicated all
# copyright and related and neighboring rights to this software to the
# public domain worldwide. This software is distributed without any
# warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication
# along with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.
#
# SPDX-License-Identifier: CC0-1.0


# >= 4.3.7: () { emulate -L sh; . ~/.profile; }
# >= 4.3.10: emulate sh -c '. ~/.profile'
source_sh_profile() {
    emulate -L sh
    . ~/.profile && unset -f -- "$0"

    # https://www.zsh.org/mla/users/2008/msg00785.html (users/13169)
    # < 4.3.7: Options are restored at function exit but emulation mode is
    # not. Explicitly revert to zsh mode, or things get weird later.
    emulate -L zsh
}
source_sh_profile

# Source topic scripts.
save_vars LC_COLLATE
LC_COLLATE=C
for script in dummy $ZDOTDIR/zprofile.d/*.zsh(N-^/); do
    if [[ $script = dummy ]]; then
        restore_vars LC_COLLATE
    else
        . $script
    fi
done
unset script
