ZDOTDIR=~/.zsh

# I can't think of a good reason to allow duplicates in these.
typeset -U FPATH fpath PATH path

fpath=($ZDOTDIR/functions(N) $fpath)

# Source application-specific "topic" scripts.
for script in $ZDOTDIR/zshenv.d/*.zsh(N-.); do
    . $script
done
unset script

# vim: set filetype=zsh:
