# zsh/_zsh/zshenv
# ---------------
#
# Written in 2012-2016, 2018, 2020-2022 by Lawrence Velazquez
# <vq@larryv.me>.
#
# To the extent possible under law, the author(s) have dedicated all
# copyright and related and neighboring rights to this software to the
# public domain worldwide.  This software is distributed without any
# warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication
# along with this software.  If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.
#
# SPDX-License-Identifier: CC0-1.0


: ${ZDOTDIR:=~/.zsh}

# I can't think of a good reason to allow duplicates in these.
typeset -U FPATH fpath PATH path

fpath=($ZDOTDIR/functions(N) $fpath)

# Source topic scripts.
sourced_scripts=
for script in $ZDOTDIR/zshenv.d/*.zsh(N-^/); do
    . $script
done
unset script

# Login and interactive shells will do this later.
if [[ ! -o LOGIN && ! -o INTERACTIVE ]]; then
    unset_sh_helper_functions 2>/dev/null
    unset -f emulated_eval 2>/dev/null
    unset sourced_scripts
fi
