. ~/.profile.d/functions.sh

ZDOTDIR=~/.zsh

# I can't think of a good reason to allow duplicates in these.
typeset -U FPATH fpath PATH path

fpath=($ZDOTDIR/functions(N) $fpath)

# Source application-specific "topic" scripts.
save_vars LC_COLLATE
LC_COLLATE=C
for script in dummy $ZDOTDIR/zshenv.d/*.zsh(N-.); do
    if [[ $script = dummy ]]; then
        restore_vars LC_COLLATE
    else
        . $script
    fi
done
unset script

# Login and interactive shells will do this later.
if [[ ! -o LOGIN && ! -o INTERACTIVE ]]; then
    unset_sh_helper_functions
fi
