#!/bin/sh

# -----
# Install script for Mercurial setup.
#
# Usage: sh setup [-f] [TARGET]
# -----

# Source shared functions, etc.
. ../common.sh || exit 2

# TODO: Try to factor out common script-level options.
hg_FORCE=$FORCE
while getopts f opt; do
    case $opt in
        f) hg_FORCE=-f ;;
    esac
done
shift $(($OPTIND - 1))

hg_SOURCES=hgrc
hg_TARGET=${1:-${TARGET:-$HOME}}

CreateAbsoluteSymlinks -d $hg_FORCE $hg_SOURCES "$hg_TARGET"
