#!/bin/sh

# -----
# Install script for Lynx setup.
#
# Usage: sh setup [-f] [TARGET]
# -----

# Source shared functions, etc.
. ../common.sh || exit 2

# TODO: Try to factor out common script-level options.
lynx_FORCE=$FORCE
while getopts f opt; do
    case $opt in
        f) lynx_FORCE=-f ;;
    esac
done
shift $(($OPTIND - 1))

lynx_TARGET=${1:-${TARGET:-$HOME/.lynx}}
mkdir -p "$lynx_TARGET"
CreateAbsoluteSymlinks $lynx_FORCE lynx.cfg "$lynx_TARGET"
