#!/bin/sh

# -----
# Install script for tmux setup.
#
# Usage: sh setup [-f] [TARGET]
# -----

# Source shared functions, etc.
. ../common.sh || exit 2

# TODO: Try to factor out common script-level options.
tmux_FORCE=$FORCE
while getopts f opt; do
    case $opt in
        f) tmux_FORCE=-f ;;
    esac
done
shift $(($OPTIND - 1))

# Install tmux configuration.
tmux_SOURCES=tmux.conf
tmux_TARGET=${1:-${TARGET:-$HOME}}
CreateAbsoluteSymlinks -d $tmux_FORCE $tmux_SOURCES "$tmux_TARGET"

# Install zsh customizations.
tmux_SOURCES=tmux.zsh
# TODO: Support custom zsh configuration location.
mkdir -p "$HOME/.zsh/interactive"
CreateAbsoluteSymlinks $tmux_FORCE $tmux_SOURCES "$HOME/.zsh/interactive"
