#!/bin/sh

# -----
# Install script for zsh setup.
#
# Usage: sh setup [-f]
# -----

# Source shared functions, etc.
. ../common.sh || exit 2

# TODO: Try to factor out common script-level options.
zsh_FORCE=
while getopts f opt; do
    case $opt in
        f) zsh_FORCE=-f ;;
    esac
done
shift $(($OPTIND - 1))

# Link .zshenv, which will point zsh to an alternative ZDOTDIR.
zsh_SOURCES=zshenv
# TODO: Support customized target directory.
zsh_TARGET_DIR=$HOME
CreateAbsoluteSymlinks -d $zsh_FORCE $zsh_SOURCES "$zsh_TARGET_DIR"

# Link the other dotfiles into the alternative ZDOTDIR.
zsh_SOURCES='zlogin zshrc'
zsh_TARGET_DIR=$zsh_TARGET_DIR/.zsh
mkdir "$zsh_TARGET_DIR"
CreateAbsoluteSymlinks -d $zsh_FORCE $zsh_SOURCES "$zsh_TARGET_DIR"
