#!/bin/sh

# -----
# Install script for zsh setup.
#
# Usage: sh setup [-f] [TARGET]
# -----

# Source shared functions, etc.
. ../common.sh || exit 2

# TODO: Try to factor out common script-level options.
zsh_FORCE=$FORCE
while getopts f opt; do
    case $opt in
        f) zsh_FORCE=-f ;;
    esac
done
shift $(($OPTIND - 1))

# Link .zshenv, which will point zsh to an alternative ZDOTDIR.
zsh_SOURCES=zshenv
zsh_TARGET=${1:-${TARGET:-$HOME}}
mkdir -p "$zsh_TARGET"
CreateAbsoluteSymlinks -d $zsh_FORCE $zsh_SOURCES "$zsh_TARGET"

# Link the other dotfiles into the alternative ZDOTDIR.
zsh_SOURCES='zlogin zshrc'
mkdir "$HOME/.zsh"
CreateAbsoluteSymlinks -d $zsh_FORCE $zsh_SOURCES "$HOME/.zsh"
