#!/bin/sh

# -----
# Install script for zsh setup.
#
# Usage: sh setup [-f]
# -----

# Source shared functions, etc.
. ../common.sh || exit 2

# TODO: Try to factor out common script-level options.
zsh_FORCE=
while getopts f opt; do
    case $opt in
        f) zsh_FORCE=-f ;;
    esac
done
shift $(($OPTIND - 1))

zsh_SOURCES=z*
# TODO: Support customized target directory.
zsh_TARGET_DIR=$HOME

CreateAbsoluteSymlinks -d $zsh_FORCE $zsh_SOURCES "$zsh_TARGET_DIR"
