# Most of these options are here because I don't want them to
# override preexisting environment variables from a calling shell.
# They are desirable for a login shell though.

export EDITOR='/usr/bin/env vim'
export GREP_OPTIONS='--color=auto'
export PAGER='/usr/bin/env less'

# Set JAVA_HOME dynamically, if a JVM is installed
if [[ ${OSTYPE} == darwin* ]]; then
    export JAVA_HOME="$(/usr/libexec/java_home -F 2> /dev/null)"
    [[ -z ${JAVA_HOME} ]] && unset JAVA_HOME
fi

# Source any "topic" scripts. Customizations to enhance the
# functionality of external programs should be placed in
# $ZDOTDIR/startup.
for script in ${ZDOTDIR}/startup/*.zlogin(N); do
    . ${script}
done
